# Generated by Django 2.2 on 2019-04-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectModel',
            fields=[
                ('ModelName', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('DetectAlgorithm', models.CharField(max_length=16)),
                ('FeatureConfig', models.TextField()),
                ('FileType', models.CharField(max_length=8)),
                ('DetectFile', models.BinaryField()),
                ('ctime', models.DateTimeField(auto_now=True)),
                ('uptime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
